### PR TITLE
Release v2.1.0

### PR DESCRIPTION
**Pull request by BernhardWebstudio**
- add support for `git stash` (new feature)
- upgrades of PHPUnit
- add typehints were possible
- fix issues #121, #123, #124

### CODE REVIEW

**Comment by Imunhatep** [comment]
I'm fine to release v2.1. Just a minor question - are you suggesting to squash commits?  cause I used to merge directly, saving commit history..

**Comment by BernhardWebstudio** [comment]
I am sorry, what commits are you referencing to? I am sorry, if I did squash any commits, it was by accident, although I am pretty sure I paid attention to execute the commands as they were suggested by GitHubs merge instructions...

**Comment by Imunhatep** [comment]
No no, I mean github currently (for this MR) suggests to "Squash and merge" (check green button for merging) and I was wondering if this is default behavior for github or this is MR specific and could be controlled by MR issuer?!

**Comment by BernhardWebstudio** [comment]
Ah sorry, yeah, without squashing is alright. For me, somehow, 
squashing is not the default. But yeah, I will then proceed to publish, thanks.

**Pull request merged**
