### PR TITLE
 - php7.2 is now supported

### PR DESCRIPTION
**Pull request by Imunhatep**
- renamed *GitElephant\Objects\Object* to *GitElephant\Objects\NodeObject*
 - updated Phpunit to version 6, Tests, README
 - minimal supported php7.0 (technically only phpunit6 requires php > 7, otherwise requirements can be lowered)

### CODE REVIEW

**Comment by matteosister** [comment]
awesome work! :heart: I'll merge this soon...

**Comment by matteosister** [comment]
I've seen you removed php 5 from the build matrix. It seems a big move...but I'm not much into php anymore. Do you think that this could be a good moment to release a 2.0 version and drop 5.x support?

**Comment by matteosister** [comment]
and why removing composer.lock? Is it ok?

**Comment by franzliedke** [comment]
Library projects don't need to include composer.lock, it's mostly ignored anyway (when installed as a dependency). The lockfile is mostly meant for application projects, which use Composer to manage their dependencies, so that all developers / installations get the exact same versions of dependencies.

**Comment by Imunhatep** [comment]
Technically php7.0 is not supported since 3. dec 2018. Supporting last 2 versions is a very popular approach, so yes, I think it's a good moment for 2.0 and hope that U do so. For projects on php5, there will be an option to use 1.x. 
About composer.lock @franzliedke have answered.

**Comment by Xen3r0** [comment]
Hi,

Can you merge this PR & make a release plz ?

Thanks

**Comment by BernhardWebstudio** [comment]
Dear @matteosister , I would like to thank you for this project, but also ask you nicely if you could please merge this PR? The upgrade of a server to php 7.2 leads to a crashing application because of compile errors emerging from the suboptimal naming of that one class. Thanks!

**Comment by matteosister** [comment]
Hello everybody! sorry for the delay...but I really don't have time to put into this library :(
I'm also not involved in php anymore, so it's becoming even more difficult to manage this repository and its prs. Does anybody want access to the repository and want to take the reponsibility of pushing it forward?

I really don't have time, but I don't like to let anyone down.

**Comment by matteosister** [comment]
@BernhardWebstudio @Imunhatep @Xen3r0 @franzliedke anyone?

**Comment by Xen3r0** [comment]
Sorry, I can not take responsibility, I do not have time :( i can contribute, but not take responsibility

**Comment by BernhardWebstudio** [comment]
Responsibility is a huge word. I am willing to take some, but I doubt that my time is enough to take all, and would prefer if I could share it with someone.

**Comment by Imunhatep** [comment]
Well if we compare several maintainers with little time to one maintainer without time.. the choice seems obvious, since the other option is that library will become abandoned. We may at least try. Once in a month I may check MRs and issues.

**Comment by matteosister** [comment]
@Imunhatep thanks!
So do you want push access to the repo? Let's see if we can manage to tag a 2.0 release with php 7 support?

**Comment by BernhardWebstudio** [comment]
Would be awesome if we could keep this repo going! Would you mind giving the permissions for the matching Symfony-Bundle too, @matteosister, so it stays up to date with this one?

**Comment by matteosister** [comment]
done! :+1:

**Comment by Imunhatep** [comment]
@matteosister Do I want it? No ) But there is no other way since I agreed to help BernhardWebstudio in keeping eye on this repo. If you'll give me push permissions I'll merge this issue to develop, merge it with master and tag it with v2.0.0.

**Comment by matteosister** [comment]
@Imunhatep thanks! Done...

**Pull request merged**
