### PR TITLE
update to php 7.1

### PR DESCRIPTION
**Pull request by rvitaliy**
based on the php roadmap http://php.net/supported-versions.php
I would propose to update the php requirement of the project to version "^7.1"

### CODE REVIEW

**Comment by BernhardWebstudio** [comment]
Thanks for your contribution! What is the benefit of dropping support for symfony components 3.x?

**Comment by rvitaliy** [comment]
they're not support php 7
https://github.com/symfony/filesystem/blob/3.2/composer.json
but i see they start to support it from >= 3.3
https://github.com/symfony/filesystem/blob/3.3/composer.json
so we can change requirements to `"symfony/filesystem": "^3.3|^4.0"`

**Comment by BernhardWebstudio** [comment]
That is not true. Just because they do not require PHP 7 does not mean they do not support it – I was running a full Symfony 2.8 application (untill recently when I upgraded) successfully under PHP 7.2...

**Comment by rvitaliy** [comment]
I misunderstood the behavior of the composer, sorry, i rollback the changes.

**Comment by Imunhatep** [comment]
As I understand there is nothing to merge?! Can we close this MR?

**Pull request closed without merging**
