### PR TITLE
#28 Added git stash support

### LINKED ISSUE #28: implement git stash

### PR DESCRIPTION
**Pull request by kirkmadera**
Adds support for git stash commands. Resolves #28

### CODE REVIEW

**Comment by kirkmadera** [comment]
Errors in TravisCI are not related to the code changes in this PR.

**Comment by matteosister** [comment]
awesome thanks! I'll merge and release asap.

**Comment by kirkmadera** [comment]
I noticed that addCommandSubject() has a string typehint, but the underlying code also deals with arrays and objects. This generates [this error in Scruitnizer](https://scrutinizer-ci.com/g/matteosister/GitElephant/inspections/102a15cd-903a-4bf5-a206-6c8ded99eeaa/issues/files/src/GitElephant/Command/StashCommand.php?status=new&orderField=path&order=asc&honorSelectedPaths=0) that can only be fixed by changing the typehint. I didn't want to do that as part of this PR.

**Comment by matteosister** [comment]
I'll fix it on master, Thanks!

**Comment by matteosister** [comment]
I had to revert everything, there are many problems with old php version like:
 - using (Foo::bar($this))->method()
 - the short array syntax

and also there is a function named **list**, which is a [reserved](https://secure.php.net/manual/en/reserved.keywords.php) word

**Comment by matteosister** [comment]
@kirkmadera if you want to open a new pull request I'll be happy to review it.

**Comment by kirkmadera** [comment]
I moved it over into my namespace so it's a new pull request. Please see https://github.com/matteosister/GitElephant/pull/132.

I switched my PHPStorm to PHP 5.3 and resolved all notices. I went a little beyond the scope of this issue, but only in documentation. Hope that's ok.

**Pull request merged**
